@startuml
boundary PantallaConsultarEncuesta as pa
control ControlConsultarEncuesta as ge
participant ":IIteradorLlamada" as ill
entity llamada as ll
participant ":IIteradorCambioEstado" as ilc
entity cambioEstado as ce
entity "EstadoInicial:CambioEstado" as ice
entity Estado as e

ge -> ge: buscarLlamadasRespondidas()
ge -> ge: crearIterador():IIterador
ge --> ill: new(elem:Llamada[],filtros:Object[])
ge -> ill: primero()
group loop recorrer llamadas [haTerminado := false]
ge -> ill: haTerminado():boolean
ge -> ill: elementoActual():Llamada
ill -> ill: cumpleFiltro():boolean
ill -> ll: esDePeriodo(fechaHoraInicio:Date,fechaHoraFin:Date):boolean
ll -> ll: crearIterador():IIterador
ll --> ilc: new(elem:CambioEstado[],filtros:Object[])
ll -> ilc: primero()
group loop recorrer cambios de estado [haTerminado := false]
ll -> ilc: haTerminado():boolean
ll -> ilc: elementoActual():CambioEstado
ilc -> ilc: cumpleFiltro():boolean
ilc -> ce: esEstadoInicial():boolean
ce -> e: esIniciada():boolean
ll -> ilc: siguiente()
end
ll ->ilc: elementoActual():CambioEstado
ll -> ice: getFechaHoraInicio()
ill -> ll: tieneEncuestaRespondida()
ill -> ge: agregarLlamadaEnPeriodo(llamada:Llamada)
ge -> ill: siguiente()
end
ge -> pa: actualizarTablaLlamadas()

@enduml
