@startuml
class GestorReporteReclamos{
  clientesSeleccionados
  fechaActual
  fechaDesde
  fechaHasta
  formaVisualizacion
  tasaPorCLiente
  tipoTasa

  calcularTasaCliente()
  crearEstrategia()
  crearIterador()
  generarReporte()
  tomarSeleccionTipoTasa()
}
class IEstrategiaTasaReclamos <<interface>>{
  calcularTasaClientes(fechadesde, fechahasta, clientesSeleccionados,pedidos)
}
class TasaBruta <<estrategia>>{
  calcularTasaCliente(fechaDesde, fechaHasta, clientesSeleccionados,pedidos)
  new()
}
class TasaNoCrititcos <<estrategia>>{
  calcularTasaCliente(fechaDesde, fechaHasta, clientesSeleccionados,pedidos)
  new()
}
class TasaCriticos <<estrategia>>{
  calcularTasaCliente(fechaDesde, fechaHasta, clientesSeleccionados,pedidos)
  new()
}
class PantallaGeneracionReportesReclamos <<boundary>>{
  cmbTipoTasa
  tomarSeleccionTipoTasa()
}
note "contexto" as n1 #pink
n1 .. GestorReporteReclamos

note left of  IEstrategiaTasaReclamos #pink
"Estrategia"
end note

note "Estrategias Concretas" as n2 #pink
TasaBruta .. n2
TasaNoCrititcos .. n2
TasaCriticos .. n2

GestorReporteReclamos .. IEstrategiaTasaReclamos
IEstrategiaTasaReclamos <|-- TasaBruta
IEstrategiaTasaReclamos <|-- TasaNoCrititcos
IEstrategiaTasaReclamos <|-- TasaCriticos
PantallaGeneracionReportesReclamos .. GestorReporteReclamos
@enduml
